name: Automated API tests using Newman

on:
  workflow_dispatch:
  push:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Newman
        run: |
          npm install -g newman
      - name: Install HTMLextra
        run: |
          npm i newman-reporter-htmlextra
      - name: Run API tests
        run: |
          newman run github_actions_example.postman_collection.json -e git_action_test.postman_environment.json -r htmlextra,cli
